# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smooth}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jakob Holderbaum"]
  s.date = %q{2011-03-22}
  s.description = %q{extends haml with useful helpers, a layout concept and rails-partial like components.}
  s.email = %q{jh@neopoly.de}
  s.files = [
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "api-example.haml",
    "comp/slides.haml",
    "lib/smooth.rb",
    "lib/smooth/base.rb",
    "lib/smooth/helpers.rb",
    "lib/smooth/helpers/about.rb",
    "lib/smooth/helpers/components.rb",
    "lib/smooth/helpers/content_store.rb",
    "lib/smooth/helpers/slides.rb",
    "test.watchr",
    "test/base_test.rb",
    "test/fixtures/components/path1/comp1.haml",
    "test/fixtures/components/path1/missing.haml",
    "test/fixtures/components/path1/with_block.haml",
    "test/fixtures/components/path1/with_block_and_arg.haml",
    "test/fixtures/components/path1/with_block_and_arg_and_title.haml",
    "test/fixtures/components/path1/with_block_and_title.haml",
    "test/fixtures/components/path2/comp2.haml",
    "test/helper.rb",
    "test/helpers_about_test.rb",
    "test/helpers_components_test.rb",
    "test/helpers_content_store_test.rb",
    "test/helpers_slides_test.rb"
  ]
  s.homepage = %q{http://techfolio.de}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{create nice haml slides (powered by slippy)}
  s.test_files = [
    "test/base_test.rb",
    "test/helper.rb",
    "test/helpers_about_test.rb",
    "test/helpers_components_test.rb",
    "test/helpers_content_store_test.rb",
    "test/helpers_slides_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

